---
output:
  html_document:
        toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T)
source("0_packages.R")
source(".statapath.R")

```

# Prepare Data for Models {.tabset}
***

## Stata
```{r, results = T, engine = "stata", engine.path= statapath, comment = ""}
use "_data/ess50.dta", clear

*** Preparing Data
* country-string to country-integer
cap drop id
egen id = group(cntry)

* democracy variable 
cap drop new
gen new = (id == 7 | id == 20 | id == 11)

cap drop newest
gen newest = (id == 4 | id == 12 | id == 19 | id == 22)

cap drop old
gen old = (new == 0 & newest == 0)

save "_data/ess50prep.dta", replace
```

## R
```{r}
ess          <- read_dta("_data/ess50.dta")
# ess          <- select(ess, cntry, stfdem, female, hinctnt, polintr, nwsptot)
ess$cntry.nr <- as.numeric(as.factor(ess$cntry))

# Country numbers
new.nr     <- c(7, 20, 11)
newest.nr  <- c(4, 12, 19, 22)
old.nr     <- setdiff(1:22, c(new.nr, newest.nr))

# Democracy dummies
ess$new    <- ifelse(ess$cntry.nr %in% new.nr, 1, 0)
ess$newest <- ifelse(ess$cntry.nr %in% newest.nr, 1, 0)
ess$old    <- ifelse(ess$cntry.nr %in% old.nr, 1, 0)

# transform factors
ess <- ess %>% 
      mutate(f.polintr = as_factor(polintr),
             f.nwsptot = as_factor(nwsptot),
             f.gndr = as_factor(gndr)
      )
             
# Save and load data
save(ess, file = "_data/ess50prep.Rds")
load("_data/ess50prep.Rds")
```

