---
output:
  html_document:
    code_folding: "show"
    df_print: paged
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T)
statapath = "/Applications/Stata/StataMP.app/Contents/MacOS/Stata-MP"

source("0_packages.R")

load("../data/ess50prep.Rds")
```

# 4.1 Cross-Level Interaction Model {.tabset}

## Model Data {.tabset}
### Model
#### Stata
```{r, results = T, engine = "stata", engine.path= statapath, comment = ""}
use "../data/ess50prep.dta", clear

xtmixed stfdem polintr nwsptot gndr##newest gndr##new || cntry: gndr, cov(unstructured)
estat icc
```

#### R
```{r}
multi4 <- lmer(stfdem ~ polintr + nwsptot + (gndr * new) + (gndr * newest) + (1  + gndr |cntry), data = ess, REML = FALSE)
```

```{r}
tidy(multi4)
glance(multi4)
icc(multi4)
```


## 4.2 Fixed Effects Plots
#### Fixed effects
p-values approximated by Wald-Statistics with `p.kr = FALSE` -> reduces computing time signficantly
```{r}
sjp.lmer(multi4, type = "fe", p.kr = FALSE)
```

#### Standardized Fixed effects
```{r warning = FALSE}
sjp.lmer(multi4, type = "fe.std", p.kr = FALSE)
```

#### Slopes of fixed effects
```{r warning = FALSE}
sjp.lmer(multi4, type = "fe.slope", vars = c("newest", "polintr"))
```
