---
output:
  html_document:
    code_folding: "show"
    df_print: paged
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T)

source("0_packages.R")

load("../data/ess50prep.Rds")
```

# 7. EDV Regression {.tabset}

### Code
#### Stata
```{r, engine='stata-mp'}
* not available anymore
```

#### R
```{r}
### EDV-Reg
ess %>% 
  group_by()
ess_group <- group_by(ess, cntry)
ess

multi6 <- lmer(stfdem ~ (1|cntry/region), data = ess_group, REML = FALSE)

ess %>%
  split(.$cntry) %>%
  map(~ lm(stfdem ~ polintr, data = .)) %>%
  map(summary) %>%
  map_dbl("r.squared") %>% 
  str()

ess %>%
  split(.$cntry) %>%
  map(~ lm(stfdem ~ polintr, data = .)) %>%
  map(summary) %>%
  map("residuals") %>% 
  map(~ var(.)) %>% 
  unlist() ->
  var.res

ess %>%
  split(.$cntry) %>%
  map(~ lm(stfdem ~ polintr, data = .)) %>%
  map(summary) %>%
  map("coefficients") ->
  coeff

coeff %>% 
  as.data.frame() %>% 
  as.tibble() %>% 
  select(ends_with("Estimate")) %>% 
  .[2, ] %>% 
  as.data.frame() %>% 
  unlist() ->
  coeff2

var.res
coeff


# ess %>%
#   drop_na() %>% 
#   group_by(cntry.nr) %>% 
#   mutate_at(vars(polintr, nwsptot), funs(mean = mean(.)), 
#             vars(polintr_mean, nwsptot_mean), funs(dev = . - mean)) %>% 
#   print()
#Fehler in mutate_impl(.data, dots) : Evaluation error: Argument kann nicht als logischer Wert interpretiert werden.


var.res %>% 
  as.data.frame() %>% 
  t()

ess %>% 
  group_by(cntry) %>% 
  summarise_all(., funs(mean = mean(.))) ->
  ess.agreggated
View(ess.agreggated)

model <- edvreg()

# res <- edvreg(y ~ x, omegasq = est.var.y )
# model <- edvreg(polint ~ new + newest omegasq = )

new_dummy <- 1:22 %in% new.nr
newest_dummy <- 1:22 %in% newest.nr
old_dummy <- 1:22 %in% old.nr

model <- edvreg(coeff2 ~ new_dummy + newest_dummy, omegasq = var.res)


inter <- lmer(stfdem ~ (polintr * new) + (polintr * newest) + (1  + polintr |cntry), data = ess, REML = FALSE)

inter

ess %>%
  drop_na() %>% 
  group_by(cntry.nr) %>% 
  mutate_all(. , funs(mean = mean(.))) %>% 
  print()



map %>% as.data.frame()
unlist(map)
model <- lm(stfdem ~ polintr, data = ess)
model %>% str()
model$residuals
var(model$residuals)
summary(model) %>% str()
```