---
output:
  html_document:
    code_folding: hide
    df_print: paged
    toc: true
    toc_float: true
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
source("0_packages.R")

knitr::opts_chunk$set(echo = TRUE, cache = T)
statapath = "/Applications/Stata/StataMP.app/Contents/MacOS/Stata-MP"

```

# Exercise 5 {.tabset}
## Questions

5.1 Apply a chow-test for structural change on the returns to education and the gender wage gap comparing the years 2005 and 2015.

## Data Prep {.tabset}
### Stata
```{r stata create and clean, results = T, engine = "stata", engine.path= statapath, comment = ""}
set more off
capt clear
version 14

use "_data/ex_mydf.dta", clear
```
### R
#### Load Data
```{r load data}
#### load dataset ####
# https://stackoverflow.com/questions/29012141/between-and-within-standard-deviation-of-panel-data-in-r


#### load dataset ####
ex_mydf <- readRDS(file = "_data/ex_mydf.rds")

asample <- ex_mydf %>% 
      filter(
            # Working Hours
            pgtatzeit >= 6,
            # age
            alter %>% dplyr::between(18, 65),
            # Employment Status
            pgemplst %in% c(1,2,4),   # full-time(1), part-time(2), marg.-empl(4)
            # population status
            pop < 3 # only private households
            ) %>%
      # filter unplausible cases
      mutate(na = case_when(
              pid %in% c(1380202, 1380202, 607602, 2555301) ~ 1,
              pid == 8267202 & syear == 2007 ~ 1,
              pid == 2633801 & syear == 2006 ~ 1,
              pid == 2582901 & syear > 2006 ~ 1 )
             ) %>% 
      filter(is.na(na)) %>% 
      dplyr::select(syear, pgbilzeit, frau, ost, lnwage, erf)

```

## Answers {.active}
### 5.1 {.tabset}
Apply a chow-test for structural change on the returns to education and the gender wage gap comparing the years 2005 and 2015.

***

#### Stata
```{r, results = T, engine = "stata", engine.path= statapath, comment = ""}
use "_data/ex_mydf.dta", clear

*** Pooled OLS
* 2015
reg lnwage ost frau pgbilzeit c.erf##c.erf pgexpue i.pgallbet if asample==1 & syear==2015 [pw=phrf], cluster(hid)
estimates store m2015

* 2005
reg lnwage ost frau pgbilzeit c.erf##c.erf pgexpue i.pgallbet if asample==1 & syear==2005 [pw=phrf], cluster(hid)
estimates store m2005

gen per2015 = syear == 2015
reg lnwage ost frau pgbilzeit c.erf##c.erf pgexpue i.pgallbet per2015 if asample==1 & syear==2005 | syear==2015 [pw=phrf], cluster(pid)
estimates store pooled

esttab m2005 m2015 pooled , ar2 abs star(* .05 ** .01) replace nobase ///
nobase mtitle("2005" "2015" "pooled") nogaps

esttab m2005 m2015 pooled using table.rtf  , ar2 abs star(* .05 ** .01) replace ///
nobase mtitle("2005" "2015" "pooled")

*** Test for structural change
reg lnwage i.per2015##i.ost i.per2015##i.frau  i.per2015##c.pgbilzeit c.erf##c.erf pgexpue i.pgallbet per2015 if asample==1 & syear==2005 | syear==2015 [pw=phrf], cluster(pid)

reg lnwage ost frau pgbilzeit c.erf##c.erf pgexpue i.pgallbet if asample==1 & syear==2015 [iw=phrf], 
estimates store m2015
reg lnwage ost frau pgbilzeit c.erf##c.erf pgexpue i.pgallbet if asample==1 & syear==2005 [iw=phrf],
estimates store m2005

suest m2005 m2015  , cluster(hid)

est table m2005 m2015, star

test [m2005_mean = m2015_mean] 

test [m2005_mean]pgbilzeit=[m2015_mean]pgbilzeit
 

test [f1_mean]alter = [m1_mean]alter
test [f1_mean]_cons = [m1_mean]_cons
```
 
#### R {.tabset .active}
##### Test
Chow Test
```{r model 5.1}
dv05 <- asample %>% 
      mutate(erf_q = erf^2) %>% 
      filter(syear == 2005) %>%
      drop_na() %>% 
      pull(lnwage)

dv15 <- asample %>% 
      mutate(erf_q = erf^2) %>% 
      filter(syear == 2015) %>%
      drop_na() %>% 
      pull(lnwage)  

ivs05 <- asample %>% 
      mutate(erf_q = erf^2) %>% 
      filter(syear == 2005) %>%
      drop_na() %>% 
      select(-lnwage) %>%
      as.matrix()

ivs15 <- asample %>% 
      mutate(erf_q = erf^2) %>% 
      filter(syear == 2015) %>%
      drop_na() %>% 
      select(-lnwage) %>%
      as.matrix() 

sctest(c(dv05, dv15) ~ rbind(ivs05, ivs15), type = "Chow", point = length(dv05), data = asample)
```

##### Plot

https://thetarzan.wordpress.com/2011/06/16/the-chow-test-in-r-a-case-study-of-yellowstones-old-faithful-geyser/