<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title></title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 52px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 57px;
  margin-top: -57px;
}

.section h2 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h3 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h4 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h5 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h6 {
  padding-top: 57px;
  margin-top: -57px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Panel- and Multilevel Models</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Panel Exercises
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="ex1_soep.html">Ex1</a>
    </li>
    <li>
      <a href="ex2_soep.html">Ex2</a>
    </li>
    <li>
      <a href="ex3_soep.html">Ex3</a>
    </li>
    <li>
      <a href="ex4_soep.html">Ex4</a>
    </li>
    <li>
      <a href="ex5_soep.html">Ex5</a>
    </li>
    <li>
      <a href="ex6_soep.html">Ex6</a>
    </li>
    <li>
      <a href="ex7_soep.html">Ex7</a>
    </li>
    <li>
      <a href="ex8_soep.html">Ex8</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Random Intercept</li>
    <li>
      <a href="1_rimodel.html">1. without independent variable</a>
    </li>
    <li>
      <a href="2_rimodel.html">2. with independent variable</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="3_rcmodel.html">3. Random Coefficient</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="4_crosslevelint.html">4. Cross-Level Interaction</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="5_crossclass.html">5. Cross-Classified</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="6_3level.html">6. Three Level</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="7_lrtest.html">7. Likelihood Ratio test</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Data Preparation
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="ex0_create.html">Exercises</a>
    </li>
    <li>
      <a href="0_create.html">Models</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/TripLLL">
    <span class="fa fa-github"></span>
     
    
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>




</div>


<div id="exercise-2" class="section level1 tabset">
<h1>Exercise 2</h1>
<div id="questions" class="section level2">
<h2>Questions</h2>
<ul>
<li><p>2.1 Estimate a Linear Regression with SOEP Data using hourly wage <code>hwageb</code> as dependent variable for the year 2015. Include years of schooling <code>pgbilzeit</code> and work experience <code>erf</code> as predictor variables and gender <code>frau</code> and region <code>ost</code> as additional controls.</p></li>
<li><p>2.2 Interpret the coefficients and the value of R²</p></li>
<li><p>2.3 Is the relationship between work experience and wage linear?</p></li>
<li><p>2.4 Specifiy the same regression model but use the natural logarithm as dependent variable instead.</p></li>
<li><p>2.5 How large is the gender pay gap?</p></li>
</ul>
</div>
<div id="data-prep" class="section level2 tabset">
<h2>Data Prep</h2>
<div id="stata" class="section level3">
<h3>Stata</h3>
<pre class="stata"><code>use &quot;_data/ex_mydf.dta&quot;, clear

* Unplausible Beobachtungen identifizieren
********************************************************************************
      twoway (scatter hwageb pgtatzeit, msymbol(point) jitter(2))

* Visualize Income
********************************************************************************
      histogram hwageb if asample==1, bin(25)
    sum hwageb if asample==1, d
    twoway (scatter hwageb pgtatzeit, msymbol(point) jitter(2)) if asample==1
      </code></pre>
<pre><code>
. use &quot;_data/ex_mydf.dta&quot;, clear
(PGEN: Feb 12, 2017 13:00:53-1 DBV32L)

. 
. * Unplausible Beobachtungen identifizieren
. *****************************************************************************
&gt; ***
.       twoway (scatter hwageb pgtatzeit, msymbol(point) jitter(2))

. 
. * Visualize Income
. *****************************************************************************
&gt; ***
.       histogram hwageb if asample==1, bin(25)
(bin=25, start=0, width=30.855825)

.         sum hwageb if asample==1, d

             Hourly Brutto Income in 2015 Prices
-------------------------------------------------------------
      Percentiles      Smallest
 1%     2.169231              0
 5%     5.403614              0
10%     7.005816              0       Obs             305,838
25%     9.983869              0       Sum of Wgt.     305,838

50%     14.00146                      Mean           16.06223
                        Largest       Std. Dev.      11.46355
75%     19.18718        525.431
90%     26.40982       556.8619       Variance        131.413
95%     32.53085       559.2414       Skewness       8.248211
99%     54.21809       771.3956       Kurtosis       224.3553

.         twoway (scatter hwageb pgtatzeit, msymbol(point) jitter(2)) if asampl
&gt; e==1

.       </code></pre>
</div>
<div id="r" class="section level3 tabset">
<h3>R</h3>
<div id="load-data" class="section level4">
<h4>Load Data</h4>
<pre class="r"><code>ex_mydf &lt;- readRDS(file = &quot;_data/ex_mydf.rds&quot;)

asample &lt;- ex_mydf %&gt;% 
        filter(pgtatzeit &gt;= 6,
               !is.na(pgtatzeit),
               alter %&gt;% dplyr::between(18, 65),
               !is.na(alter),
               pgemplst %in% c(1,2,4),
               pop &lt; 3
               )  %&gt;%
      # filter unplausible cases
      mutate(na = case_when(
              pid %in% c(1380202, 1380202, 607602, 2555301) ~ 1,
              pid == 8267202 &amp; syear == 2007 ~ 1,
              pid == 2633801 &amp; syear == 2006 ~ 1,
              pid == 2582901 &amp; syear &gt; 2006 ~ 1 )
             ) %&gt;% 
      filter(is.na(na)) %&gt;% 
      select(hwageb, pgbilzeit, cpgbilzeit, erf, cerf, frau, ost, phrf, syear )

asample15 &lt;- asample %&gt;% filter(syear == 2015)</code></pre>
</div>
<div id="descriptive-pre---analysis" class="section level4">
<h4>Descriptive Pre - Analysis</h4>
<div id="unplausible-cases" class="section level5">
<h5>unplausible Cases</h5>
<pre class="r"><code># to do: show id if wage above 600
ex_mydf %&gt;% 
      select(pgtatzeit, hwageb) %&gt;% 
      drop_na() %&gt;% 
  ggplot(aes(x=pgtatzeit, y=hwageb)) + 
        geom_point(position = &quot;jitter&quot;, size = 0.21)</code></pre>
<p><img src="ex2_soep_files/figure-html/unplausible%20cases%20ex2-1.png" width="672" /></p>
<pre class="r"><code>  # nochmal scatter
  ggplot(asample, aes(x=pgbilzeit, y=hwageb)) + 
        geom_point(position = &quot;jitter&quot;, size = 0.21,
                   na.rm = T)</code></pre>
<p><img src="ex2_soep_files/figure-html/unplausible%20cases%20ex2-2.png" width="672" /></p>
</div>
<div id="visualize-income" class="section level5 tabset">
<h5>visualize Income</h5>
<div id="histogram" class="section level6">
<h6>Histogram</h6>
<pre class="r"><code>  summary(asample$hwageb)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##       0       6      10      12      14     767      19</code></pre>
<pre class="r"><code>  qplot(hwageb, geom=&quot;histogram&quot;,
        binwidth = 25,  
        main = &quot;Histogram for Hourly Wage&quot;, 
        xlab = &quot;Hourly Wage in Prices from 2015&quot;,  
        fill=I(&quot;grey&quot;), 
        col=I(&quot;black&quot;), 
        alpha= I(.2),
        xlim=c(0,500),
        ylim= c(0,125000),
        data = asample)</code></pre>
<p><img src="ex2_soep_files/figure-html/viz%20income%20ex2-1.png" width="672" /></p>
<pre class="r"><code>  # alternative
  # without ..density it would be counts
  g_hist_wage &lt;- asample %&gt;% 
        ggplot(aes(x = hwageb, y = ..density..)) +
        geom_histogram(breaks = seq(0,767.4, by = 25)) + 
        labs(title=&quot;Histogram for Hourly Wage in 2015 Prices&quot;,
             x=&quot;Hourly Wage&quot;)
  
  g_hist_wage</code></pre>
<p><img src="ex2_soep_files/figure-html/viz%20income%20ex2-2.png" width="672" /></p>
<pre class="r"><code>  hist(asample$hwageb, probability = T)</code></pre>
<p><img src="ex2_soep_files/figure-html/viz%20income%20ex2-3.png" width="672" /></p>
</div>
</div>
<div id="for-2015" class="section level5">
<h5>for 2015</h5>
<p>summary of hourly wage and yrs of schooling, work exp, etc.</p>
<pre class="r"><code>  asample %&gt;%
      filter(syear == 2015) %&gt;% 
      select(hwageb, pgbilzeit, erf, frau, ost) %&gt;%
      drop_na() %&gt;%  # optional if complete.obs is specified
      cor(use = &quot;complete.obs&quot;)</code></pre>
<pre><code>##           hwageb pgbilzeit    erf   frau    ost
## hwageb      1.00     0.366  0.210 -0.182 -0.113
## pgbilzeit   0.37     1.000 -0.104  0.037  0.042
## erf         0.21    -0.104  1.000 -0.275  0.075
## frau       -0.18     0.037 -0.275  1.000  0.016
## ost        -0.11     0.042  0.075  0.016  1.000</code></pre>
<pre class="r"><code>  asample %&gt;%
        filter(syear == 2015) %&gt;% 
        ggplot(aes(pgbilzeit, hwageb)) +
            geom_point(na.rm=T, position = &quot;jitter&quot;)</code></pre>
<p><img src="ex2_soep_files/figure-html/analysis%20for%202015-1.png" width="672" /></p>
</div>
</div>
</div>
</div>
<div id="answers" class="section level2 active">
<h2>Answers</h2>
<div id="basic-model" class="section level3 tabset">
<h3>2.1 Basic Model</h3>
<p><strong>Estimate a Linear Regression with SOEP Data using hourly wage <code>hwageb</code> as dependent variable for the year 2015. Include years of schooling <code>pgbilzeit</code> and work experience <code>erf</code> as predictor variables and gender <code>frau</code> and region <code>ost</code> as additional controls</strong>.</p>
<hr />
<p>Note: STATA command if e(sample): <em>In STATA, there is a practical command if e(sample) that lets you restrict new calculations to the observations that were used in a model calculated before. In this exercise this can be used to calculate centralized coefficients for education and compare two models with each other, making sure that they are based on the same observations. In this exercise, the basic model is calculated first (2.1) and then another model is run with the same sample, but with centralized years of education and work experience (2.1c) in order to be able to interpret the intercept in a theoretically coherent way.</em></p>
<p>Note2: STATA - R Difference concerning weights in regression models. <em>STATA and R handle weights with the value of 0 differently. While STATA drops these observations by default, R does not. In theory, weights of 0 should not exist, because sampling weights are supposed to be the inverse of the probability of being sampled. In survey data, sampling weights of 0 can be included because the weights are adjusted in various ways. If you want to include cases with 0 weights in STATA regressions you need to use the svy option as described <a href="https://www.stata.com/support/faqs/statistics/svy-and-zero-weights/">here</a>. If, on the other hand you want to exclude them from the R model, you can use a filter before modeling (e.g. <code>filter(phrf &gt; 0)</code>). For the basic model in this exercise both ways are shown here (First without 0-weight observations, then with).</em></p>
<div id="stata-1" class="section level4 tabset">
<h4>Stata</h4>
<div id="basic-model-1" class="section level5">
<h5>basic model</h5>
<p>without weights0 cases:</p>
<pre><code>  Linear regression                         Number of obs     =     14,218
                                            F(4, 14213)       =     259.84
                                            Prob &gt; F          =     0.0000
                                            R-squared         =     0.2253
                                            Root MSE          =     10.072

  ------------------------------------------------------------------------------
               |               Robust
        hwageb |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
  -------------+----------------------------------------------------------------
     pgbilzeit |   1.638184   .0619018    26.46   0.000     1.516848     1.75952
           erf |   .2431915   .0109426    22.22   0.000     .2217425    .2646405
          frau |  -2.754198   .2425546   -11.35   0.000    -3.229636   -2.278759
           ost |  -4.278906   .2718054   -15.74   0.000     -4.81168   -3.746132
         _cons |  -6.573576   .7699179    -8.54   0.000    -8.082716   -5.064436
  ------------------------------------------------------------------------------</code></pre>
<p>Note: r markdown text with STATA output: <em>Here is an example where I copied the output of the STATA regression into the R markdown in order to make it easy to compare it to the R output in the next tab. Because the STATA implementation in R markdown is not perfect yet, you cannot print single things in specific places but only run the code and see all of the output afterwards –&gt; see tab “full code”. (This is partly due to the fact that R runs STATA from shell and certain features are not available there).</em></p>
</div>
<div id="basic-model-ii" class="section level5">
<h5>basic model II</h5>
<p>with weights0 cases:</p>
<pre><code>  Survey: Linear regression
  
  Number of strata   =         1                 Number of obs     =      14,300
  Number of PSUs     =    14,300                 Population size   =  33,885,938
                                                 Design df         =      14,299
                                                 F(   4,  14296)   =      259.86
                                                 Prob &gt; F          =      0.0000
                                                 R-squared         =      0.2253
  
  ------------------------------------------------------------------------------
               |             Linearized
        hwageb |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
  -------------+----------------------------------------------------------------
     pgbilzeit |   1.638184   .0618931    26.47   0.000     1.516866    1.759503
           erf |   .2431915   .0109411    22.23   0.000     .2217455    .2646375
          frau |  -2.754198   .2425205   -11.36   0.000    -3.229569   -2.278826
           ost |  -4.278906   .2717671   -15.74   0.000    -4.811605   -3.746207
         _cons |  -6.573576   .7698095    -8.54   0.000    -8.082503    -5.06465
  ------------------------------------------------------------------------------</code></pre>
<p>Note: r markdown text with STATA output: <em>Here is an example where I copied the output of the STATA regression into the R markdown in order to make it easy to compare it to the R output in the next tab. Because the STATA implementation in R markdown is not perfect yet, you cannot print single things in specific places but only run the code and see all of the output afterwards –&gt; see tab “full code”. (This is partly due to the fact that R runs STATA from shell and certain features are not available there).</em></p>
</div>
<div id="centered-model" class="section level5">
<h5>centered model</h5>
<p>without weights0 cases:</p>
<pre><code>  Linear regression                         Number of obs     =     14,218
                                            F(4, 14213)       =     259.84
                                            Prob &gt; F          =     0.0000
                                            R-squared         =     0.2253
                                            Root MSE          =     10.072

  ------------------------------------------------------------------------------
               |               Robust
        hwageb |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
  -------------+----------------------------------------------------------------
    cpgbilzeit |   1.638184   .0619018    26.46   0.000     1.516848     1.75952
          cerf |   .2431915   .0109426    22.22   0.000     .2217425    .2646405
          frau |  -2.754198   .2425546   -11.35   0.000    -3.229636   -2.278759
           ost |  -4.278906   .2718054   -15.74   0.000     -4.81168   -3.746132
         _cons |   18.51181   .2143393    86.37   0.000     18.09168    18.93194
  ------------------------------------------------------------------------------      </code></pre>
<p>Note: r markdown text with STATA output: <em>Here is an example where I copied the output of the STATA regression into the R markdown in order to make it easy to compare it to the R output in the next tab. Because the STATA implementation in R markdown is not perfect yet, you cannot print single things in specific places but only run the code and see all of the output afterwards –&gt; see tab “full code”. (This is partly due to the fact that R runs STATA from shell and certain features are not available there).</em></p>
</div>
<div id="centered-model-ii" class="section level5">
<h5>centered model II</h5>
<p>with weights0 cases:</p>
<pre><code>  Survey: Linear regression
  
  Number of strata   =         1                 Number of obs     =      14,300
  Number of PSUs     =    14,300                 Population size   =  33,885,938
                                                 Design df         =      14,299
                                                 F(   4,  14296)   =      259.86
                                                 Prob &gt; F          =      0.0000
                                                 R-squared         =      0.2253
  
  ------------------------------------------------------------------------------
               |             Linearized
        hwageb |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
  -------------+----------------------------------------------------------------
    cpgbilzeit |   1.638184   .0618931    26.47   0.000     1.516866    1.759503
          cerf |   .2431915   .0109411    22.23   0.000     .2217455    .2646374
          frau |  -2.754198   .2425205   -11.36   0.000    -3.229569   -2.278826
           ost |  -4.278906   .2717671   -15.74   0.000    -4.811605   -3.746207
         _cons |   18.51659   .2143495    86.39   0.000     18.09644    18.93674
  ------------------------------------------------------------------------------
  </code></pre>
<p>Note: r markdown text with STATA output: <em>Here is an example where I copied the output of the STATA regression into the R markdown in order to make it easy to compare it to the R output in the next tab. Because the STATA implementation in R markdown is not perfect yet, you cannot print single things in specific places but only run the code and see all of the output afterwards –&gt; see tab “full code”. (This is partly due to the fact that R runs STATA from shell and certain features are not available there).</em></p>
</div>
<div id="full-code" class="section level5">
<h5>Full Code</h5>
<pre class="stata"><code>use &quot;_data/ex_mydf.dta&quot;, clear

* 2.1 basic model, no 0-weights
********************************************************************************
reg hwageb pgbilzeit erf frau ost if asample==1 &amp; syear==2015 [pw=phrf] 

* sum bildungszeit only for sample of last estimation
cap drop cpgbilzeit
sum pgbilzeit if e(sample)
gen cpgbilzeit = pgbilzeit - r(mean)

cap drop cerf
sum erf if e(sample)    
gen cerf = erf -r(mean)

sum pgbilzeit cpgbilzeit if e(sample)
sum erf cerf if e(sample)
    
* 2.1c model with centered predictors, no 0-weights
reg hwageb cpgbilzeit cerf frau ost if asample==1 &amp; syear==2015 [pw=phrf]


* 2.1 basic model, with 0-weights
********************************************************************************
svyset [pw=phrf]

svy: reg hwageb pgbilzeit erf frau ost if asample==1 &amp; syear==2015 

* sum bildungszeit only for sample of last estimation
cap drop cpgbilzeit
sum pgbilzeit if e(sample)
gen cpgbilzeit = pgbilzeit - r(mean)

cap drop cerf
sum erf if e(sample)    
gen cerf = erf -r(mean)

sum pgbilzeit cpgbilzeit if e(sample)
sum erf cerf if e(sample)
    
* 2.1c model with centered predictors, with 0-weights
svy: reg hwageb cpgbilzeit cerf frau ost if asample==1 &amp; syear==2015</code></pre>
<pre><code>
. use &quot;_data/ex_mydf.dta&quot;, clear
(PGEN: Feb 12, 2017 13:00:53-1 DBV32L)

. 
. * 2.1 basic model, no 0-weights
. *****************************************************************************
&gt; ***
. reg hwageb pgbilzeit erf frau ost if asample==1 &amp; syear==2015 [pw=phrf] 
(sum of wgt is   3.3886e+07)

Linear regression                               Number of obs     =     14,218
                                                F(4, 14213)       =     259.84
                                                Prob &gt; F          =     0.0000
                                                R-squared         =     0.2253
                                                Root MSE          =     10.072

------------------------------------------------------------------------------
             |               Robust
      hwageb |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
   pgbilzeit |   1.638184   .0619018    26.46   0.000     1.516848     1.75952
         erf |   .2431915   .0109426    22.22   0.000     .2217425    .2646405
        frau |  -2.754198   .2425546   -11.35   0.000    -3.229636   -2.278759
         ost |  -4.278906   .2718054   -15.74   0.000     -4.81168   -3.746132
       _cons |  -6.573576   .7699179    -8.54   0.000    -8.082716   -5.064436
------------------------------------------------------------------------------

. 
. * sum bildungszeit only for sample of last estimation
. cap drop cpgbilzeit

. sum pgbilzeit if e(sample)

    Variable |        Obs        Mean    Std. Dev.       Min        Max
-------------+---------------------------------------------------------
   pgbilzeit |     14,218    12.85849     2.77797          7         18

. gen cpgbilzeit = pgbilzeit - r(mean)
(27,340 missing values generated)

. 
. cap drop cerf

. sum erf if e(sample)    

    Variable |        Obs        Mean    Std. Dev.       Min        Max
-------------+---------------------------------------------------------
         erf |     14,218    16.53353    10.91589          0      64.48

. gen cerf = erf -r(mean)
(13,804 missing values generated)

. 
. sum pgbilzeit cpgbilzeit if e(sample)

    Variable |        Obs        Mean    Std. Dev.       Min        Max
-------------+---------------------------------------------------------
   pgbilzeit |     14,218    12.85849     2.77797          7         18
  cpgbilzeit |     14,218    1.03e-08     2.77797  -5.858489   5.141511

. sum erf cerf if e(sample)

    Variable |        Obs        Mean    Std. Dev.       Min        Max
-------------+---------------------------------------------------------
         erf |     14,218    16.53353    10.91589          0      64.48
        cerf |     14,218    1.35e-07    10.91589  -16.53353   47.94647

.         
. * 2.1c model with centered predictors, no 0-weights
. reg hwageb cpgbilzeit cerf frau ost if asample==1 &amp; syear==2015 [pw=phrf]
(sum of wgt is   3.3886e+07)

Linear regression                               Number of obs     =     14,218
                                                F(4, 14213)       =     259.84
                                                Prob &gt; F          =     0.0000
                                                R-squared         =     0.2253
                                                Root MSE          =     10.072

------------------------------------------------------------------------------
             |               Robust
      hwageb |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
  cpgbilzeit |   1.638184   .0619018    26.46   0.000     1.516848     1.75952
        cerf |   .2431915   .0109426    22.22   0.000     .2217425    .2646405
        frau |  -2.754198   .2425546   -11.35   0.000    -3.229636   -2.278759
         ost |  -4.278906   .2718054   -15.74   0.000     -4.81168   -3.746132
       _cons |   18.51181   .2143393    86.37   0.000     18.09168    18.93194
------------------------------------------------------------------------------

. 
. 
. * 2.1 basic model, with 0-weights
. *****************************************************************************
&gt; ***
. svyset [pw=phrf]

      pweight: phrf
          VCE: linearized
  Single unit: missing
     Strata 1: &lt;one&gt;
         SU 1: &lt;observations&gt;
        FPC 1: &lt;zero&gt;

. 
. svy: reg hwageb pgbilzeit erf frau ost if asample==1 &amp; syear==2015 
(running regress on estimation sample)

Survey: Linear regression

Number of strata   =         1                 Number of obs     =      14,300
Number of PSUs     =    14,300                 Population size   =  33,885,938
                                               Design df         =      14,299
                                               F(   4,  14296)   =      259.86
                                               Prob &gt; F          =      0.0000
                                               R-squared         =      0.2253

------------------------------------------------------------------------------
             |             Linearized
      hwageb |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
   pgbilzeit |   1.638184   .0618931    26.47   0.000     1.516866    1.759503
         erf |   .2431915   .0109411    22.23   0.000     .2217455    .2646375
        frau |  -2.754198   .2425205   -11.36   0.000    -3.229569   -2.278826
         ost |  -4.278906   .2717671   -15.74   0.000    -4.811605   -3.746207
       _cons |  -6.573576   .7698095    -8.54   0.000    -8.082503    -5.06465
------------------------------------------------------------------------------

. 
. * sum bildungszeit only for sample of last estimation
. cap drop cpgbilzeit

. sum pgbilzeit if e(sample)

    Variable |        Obs        Mean    Std. Dev.       Min        Max
-------------+---------------------------------------------------------
   pgbilzeit |     14,297    12.85934    2.777205          7         18

. gen cpgbilzeit = pgbilzeit - r(mean)
(27,340 missing values generated)

. 
. cap drop cerf

. sum erf if e(sample)    

    Variable |        Obs        Mean    Std. Dev.       Min        Max
-------------+---------------------------------------------------------
         erf |     14,299    16.54744    10.91855          0      64.48

. gen cerf = erf -r(mean)
(13,804 missing values generated)

. 
. sum pgbilzeit cpgbilzeit if e(sample)

    Variable |        Obs        Mean    Std. Dev.       Min        Max
-------------+---------------------------------------------------------
   pgbilzeit |     14,297    12.85934    2.777205          7         18
  cpgbilzeit |     14,297   -2.28e-08    2.777205  -5.859341   5.140659

. sum erf cerf if e(sample)

    Variable |        Obs        Mean    Std. Dev.       Min        Max
-------------+---------------------------------------------------------
         erf |     14,299    16.54744    10.91855          0      64.48
        cerf |     14,299   -8.50e-08    10.91855  -16.54744   47.93256

.         
. * 2.1c model with centered predictors, with 0-weights
. svy: reg hwageb cpgbilzeit cerf frau ost if asample==1 &amp; syear==2015
(running regress on estimation sample)

Survey: Linear regression

Number of strata   =         1                 Number of obs     =      14,300
Number of PSUs     =    14,300                 Population size   =  33,885,938
                                               Design df         =      14,299
                                               F(   4,  14296)   =      259.86
                                               Prob &gt; F          =      0.0000
                                               R-squared         =      0.2253

------------------------------------------------------------------------------
             |             Linearized
      hwageb |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
  cpgbilzeit |   1.638184   .0618931    26.47   0.000     1.516866    1.759503
        cerf |   .2431915   .0109411    22.23   0.000     .2217455    .2646374
        frau |  -2.754198   .2425205   -11.36   0.000    -3.229569   -2.278826
         ost |  -4.278906   .2717671   -15.74   0.000    -4.811605   -3.746207
       _cons |   18.51659   .2143495    86.39   0.000     18.09644    18.93674
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<div id="r-1" class="section level4 tabset active">
<h4>R</h4>
<div id="models" class="section level5 tabset">
<h5>Models</h5>
<div id="basic-model-2" class="section level6">
<h6>basic model</h6>
<p>without weights0 cases</p>
<pre class="r"><code># fit regression model
  # automatically drops rows with missing values
  fit2.1_no0w &lt;- asample15 %&gt;%
      # filter sample weights = 0
      filter(phrf &gt; 0) %&gt;% 
      lm(hwageb ~ pgbilzeit + erf + frau + ost, 
         data= ., weights = phrf)
  
  tidy(fit2.1_no0w, conf.int = T)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["conf.low"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["conf.high"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"-6.57","3":"0.4641","4":"-14","5":"3.1e-45","6":"-7.48","7":"-5.66"},{"1":"pgbilzeit","2":"1.64","3":"0.0310","4":"53","5":"0.0e+00","6":"1.58","7":"1.70"},{"1":"erf","2":"0.24","3":"0.0076","4":"32","5":"9.0e-216","6":"0.23","7":"0.26"},{"1":"frau","2":"-2.75","3":"0.1737","4":"-16","5":"3.9e-56","6":"-3.09","7":"-2.41"},{"1":"ost","2":"-4.28","3":"0.2223","4":"-19","5":"1.5e-81","6":"-4.71","7":"-3.84"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>  glance(fit2.1_no0w)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["r.squared"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["adj.r.squared"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["sigma"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["df"],"name":[6],"type":["int"],"align":["right"]},{"label":["logLik"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["AIC"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["deviance"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["df.residual"],"name":[11],"type":["int"],"align":["right"]}],"data":[{"1":"0.23","2":"0.23","3":"492","4":"1034","5":"0","6":"5","7":"-57658","8":"115328","9":"115373","10":"3.4e+09","11":"14213"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>  # summary(fit2.1_no0w)
  
  # with robust standard errors
  tidy(coeftest(fit2.1_no0w, vcov = vcovHC(fit2.1_no0w, &quot;HC1&quot;)))   # robust; HC1 (Stata default)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"-6.57","3":"0.770","4":"-8.5","5":"1.5e-17"},{"1":"pgbilzeit","2":"1.64","3":"0.062","4":"26.5","5":"1.1e-150"},{"1":"erf","2":"0.24","3":"0.011","4":"22.2","5":"1.4e-107"},{"1":"frau","2":"-2.75","3":"0.243","4":"-11.4","5":"9.4e-30"},{"1":"ost","2":"-4.28","3":"0.272","4":"-15.7","5":"2.3e-55"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="basic-model-ii-1" class="section level6">
<h6>basic model II</h6>
<p>with weights0 cases</p>
<pre class="r"><code># fit regression model
  # automatically drops rows with missing values
  fit2.1 &lt;- asample15 %&gt;%
      lm(hwageb ~ pgbilzeit + erf + frau + ost, 
         data= ., weights = phrf)
  
  tidy(fit2.1, conf.int = T)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["conf.low"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["conf.high"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"-6.57","3":"0.4641","4":"-14","5":"3.1e-45","6":"-7.48","7":"-5.66"},{"1":"pgbilzeit","2":"1.64","3":"0.0310","4":"53","5":"0.0e+00","6":"1.58","7":"1.70"},{"1":"erf","2":"0.24","3":"0.0076","4":"32","5":"9.0e-216","6":"0.23","7":"0.26"},{"1":"frau","2":"-2.75","3":"0.1737","4":"-16","5":"3.9e-56","6":"-3.09","7":"-2.41"},{"1":"ost","2":"-4.28","3":"0.2223","4":"-19","5":"1.5e-81","6":"-4.71","7":"-3.84"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>  glance(fit2.1)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["r.squared"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["adj.r.squared"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["sigma"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["df"],"name":[6],"type":["int"],"align":["right"]},{"label":["logLik"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["AIC"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["deviance"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["df.residual"],"name":[11],"type":["int"],"align":["right"]}],"data":[{"1":"0.23","2":"0.23","3":"492","4":"1034","5":"0","6":"5","7":"-57658","8":"115328","9":"115373","10":"3.4e+09","11":"14213"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>  # summary(fit2.1)
  
  coeftest(fit2.1, vcov = vcovHC(fit2.1, &quot;HC1&quot;))    # robust; HC1 (Stata default)</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -6.5736     0.7657   -8.59   &lt;2e-16 ***
## pgbilzeit     1.6382     0.0616   26.61   &lt;2e-16 ***
## erf           0.2432     0.0109   22.35   &lt;2e-16 ***
## frau         -2.7542     0.2412  -11.42   &lt;2e-16 ***
## ost          -4.2789     0.2703  -15.83   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="centered-model-1" class="section level6">
<h6>centered model</h6>
<ul>
<li><p>without weights0 cases</p></li>
<li><p>with centralized years of schooling and work experience. This can be helpful to interpret the intercept, because 0 years education are not a realistic interpretation</p></li>
</ul>
<p>Note: STATA command if e(sample) implementation in R. <em>In order to achieve the same effect of the if e(sample) addition in STATA, one can store the rownames of the observations in the fitted model and use these to filter the dataset that the next model is based on (or for whichever computation this restriction is needed).</em></p>
<pre class="r"><code>esample &lt;- rownames(as.matrix(resid((fit2.1_no0w))))

# regress again with centered predictors
fit2.1c_no0w &lt;-  asample15 %&gt;% 
  # filter only obs used in last model
  filter(row_number() %in% esample) %&gt;%
  # centralized values for education by year
  mutate(cpgbilzeit = pgbilzeit - mean(pgbilzeit, na.rm = T),
         cerf = erf - mean(erf, na.rm = T)) %&gt;% 
  # linear model
  lm(hwageb ~ cpgbilzeit + cerf + frau + ost,
     data= ., weights = phrf)
  
  tidy(fit2.1c_no0w)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"18.55","3":"0.1270","4":"146","5":"0.0e+00"},{"1":"cpgbilzeit","2":"1.63","3":"0.0316","4":"52","5":"0.0e+00"},{"1":"cerf","2":"0.24","3":"0.0078","4":"31","5":"4.6e-206"},{"1":"frau","2":"-2.82","3":"0.1771","4":"-16","5":"2.0e-56"},{"1":"ost","2":"-4.30","3":"0.2258","4":"-19","5":"6.2e-80"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>  coeftest(fit2.1c_no0w, vcov = vcovHC(fit2.1c_no0w, &quot;HC1&quot;))    # robust; HC1 (Stata default)</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  18.5457     0.2169    85.5   &lt;2e-16 ***
## cpgbilzeit    1.6350     0.0625    26.2   &lt;2e-16 ***
## cerf          0.2420     0.0110    21.9   &lt;2e-16 ***
## frau         -2.8154     0.2452   -11.5   &lt;2e-16 ***
## ost          -4.3037     0.2744   -15.7   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>  # Sample identifier, a set of row names which can be used to subset the corresponding dataframe</code></pre>
<p>Number of Observations in the sample</p>
<pre class="r"><code>length(esample)</code></pre>
<pre><code>## [1] 14218</code></pre>
</div>
<div id="centered-model-ii-1" class="section level6">
<h6>centered model II</h6>
<p>with weights0 cases</p>
<pre class="r"><code># Sample identifier, a set of row names which can be used to subset the corresponding dataframe
esample &lt;- rownames(as.matrix(resid((fit2.1))))

# regress again with centered predictors
fit2.1c &lt;-  asample15 %&gt;% 
  # filter only obs used in last model
  filter(row_number() %in% esample) %&gt;%
  # generate centralized values for education by year
  mutate(cpgbilzeit = pgbilzeit - mean(pgbilzeit, na.rm = T),
         cerf = erf - mean(erf, na.rm = T)) %&gt;% 
  # linear model
  lm(hwageb ~ cpgbilzeit + cerf + frau + ost,
     data= ., weights = phrf)
  
  tidy(fit2.1c)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"18.52","3":"0.1244","4":"149","5":"0.0e+00"},{"1":"cpgbilzeit","2":"1.64","3":"0.0310","4":"53","5":"0.0e+00"},{"1":"cerf","2":"0.24","3":"0.0076","4":"32","5":"9.0e-216"},{"1":"frau","2":"-2.75","3":"0.1737","4":"-16","5":"3.9e-56"},{"1":"ost","2":"-4.28","3":"0.2223","4":"-19","5":"1.5e-81"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>  coeftest(fit2.1c, vcov = vcovHC(fit2.1c, &quot;HC1&quot;))    # robust; HC1 (Stata default)</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  18.5170     0.2132    86.8   &lt;2e-16 ***
## cpgbilzeit    1.6382     0.0616    26.6   &lt;2e-16 ***
## cerf          0.2432     0.0109    22.4   &lt;2e-16 ***
## frau         -2.7542     0.2412   -11.4   &lt;2e-16 ***
## ost          -4.2789     0.2703   -15.8   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>  # summary statistics of education and job experience with sample of last regression
  asample15 %&gt;%
        filter(row_number() %in% esample) %&gt;% # this needs to be in a separate filter, otherwise wont work
        select(pgbilzeit, erf) %&gt;%
        stat.desc(basic = T)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["pgbilzeit"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["erf"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"1.4e+04","2":"1.4e+04","_rn_":"nbr.val"},{"1":"0.0e+00","2":"1.2e+02","_rn_":"nbr.null"},{"1":"0.0e+00","2":"0.0e+00","_rn_":"nbr.na"},{"1":"7.0e+00","2":"0.0e+00","_rn_":"min"},{"1":"1.8e+01","2":"6.4e+01","_rn_":"max"},{"1":"1.1e+01","2":"6.4e+01","_rn_":"range"},{"1":"1.8e+05","2":"2.4e+05","_rn_":"sum"},{"1":"1.2e+01","2":"1.5e+01","_rn_":"median"},{"1":"1.3e+01","2":"1.7e+01","_rn_":"mean"},{"1":"2.3e-02","2":"9.1e-02","_rn_":"SE.mean"},{"1":"4.6e-02","2":"1.8e-01","_rn_":"CI.mean.0.95"},{"1":"7.7e+00","2":"1.2e+02","_rn_":"var"},{"1":"2.8e+00","2":"1.1e+01","_rn_":"std.dev"},{"1":"2.2e-01","2":"6.6e-01","_rn_":"coef.var"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Number of Observations in the sample</p>
<pre class="r"><code>length(esample)</code></pre>
<pre><code>## [1] 14297</code></pre>
</div>
</div>
<div id="plots" class="section level5">
<h5>Plots</h5>
<pre class="r"><code># plot it 
  asample %&gt;% 
      filter(syear == 2015) %&gt;% 
      ggplot(aes(pgbilzeit, hwageb)) + 
      geom_point() + 
      geom_smooth(method=&quot;lm&quot;, color=&quot;red&quot;, se=F) +
      geom_line(aes(y = mean(asample$hwageb)), color=&quot;blue&quot;)</code></pre>
<p><img src="ex2_soep_files/figure-html/plot%20fit2.1-1.png" width="384" /></p>
<p>This code produces a set of four plots: residuals versus fitted values, a Q-Q plot of standardized residuals, a scale-location plot (square roots of standardized residuals versus fitted values) and a plot of residuals versus leverage that adds bands corresponding to Cook’s distances of 0.5 and 1. The par option is specified, in order to display all four of them at once and not in separate steps. This option is revoked afterwards. You can type ?par into R to learn more.</p>
<pre class="r"><code>par(mfrow=c(2,2))
plot(fit2.1)</code></pre>
<p><img src="ex2_soep_files/figure-html/plot2%20fit2.1-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1,1))</code></pre>
</div>
<div id="more-info" class="section level5 tabset">
<h5>More Info</h5>
<p>More Information about single parts of the model(s).</p>
<p>These are quick ways to extract the confidence intervals, intercept and slopes of a model:</p>
<pre class="r"><code># extract Confidence Intervals
      confint(fit2.1)</code></pre>
<pre><code>##             2.5 % 97.5 %
## (Intercept) -7.48  -5.66
## pgbilzeit    1.58   1.70
## erf          0.23   0.26
## frau        -3.09  -2.41
## ost         -4.71  -3.84</code></pre>
<pre class="r"><code># extract intercept
      fit2.1$coef[1]</code></pre>
<pre><code>## (Intercept) 
##        -6.6</code></pre>
<pre class="r"><code># extract slope
      fit2.1$coef[2:5]</code></pre>
<pre><code>## pgbilzeit       erf      frau       ost 
##      1.64      0.24     -2.75     -4.28</code></pre>
<pre class="r"><code># extract the names of the content in your model
      names(fit2.1)</code></pre>
<pre><code>##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;fitted.values&quot; &quot;effects&quot;      
##  [5] &quot;weights&quot;       &quot;rank&quot;          &quot;assign&quot;        &quot;qr&quot;           
##  [9] &quot;df.residual&quot;   &quot;na.action&quot;     &quot;xlevels&quot;       &quot;call&quot;         
## [13] &quot;terms&quot;         &quot;model&quot;</code></pre>
</div>
</div>
</div>
<div id="coefficients-and-r" class="section level3 tabset">
<h3>2.2 coefficients and R²</h3>
<p><strong>Interpret the coefficients and the value of R² </strong></p>
<hr />
<p><strong>Model 2.1 Coefficients</strong></p>
<ul>
<li>Intercept</li>
<li><p>The intercept is negative, which does not make theoretical sense because wages cannot be negative. Mathematically it reflects the predicted value if all explanatory variables are equal to 0. Since there is “Schulpflicht” in Germany, it is not the case that there are people with no education at all in the dataset. Since there are no observations with education &lt; 7, the model cannot predict those cases successfully. In order to be able to interpret the intercept after all, one can center the variables.</p></li>
<li>Years of Education (<code>pgbilzeit</code>)
<ul>
<li>For each unit (year) increase of education, hourly wage is expected to increase by 1.64 units (Euro).</li>
</ul></li>
<li>Work Experience (<code>erf</code>)
<ul>
<li>For each increase of working experience by one year, the expects income increases by 0,24 Euro/hour.</li>
</ul></li>
<li>Gender (<code>frau</code>)
<ul>
<li>Women are expected to earn 2.75 Euro less per hour compared to men.</li>
</ul></li>
<li>Region (<code>ost</code>)
<ul>
<li>People who grew up in former eastern germany are estimated to earn 4.26 Euro less, compared to people who grew up in former western Germany.</li>
</ul></li>
<li>R-squared
<ul>
<li>The model can explain 22.59% of the overall variance of hourly wages in Germany.</li>
</ul></li>
</ul>
<p><strong>Model 2.1c Coefficients</strong></p>
<ul>
<li>Intercept</li>
<li><p>With the variables education and work experience centered, one can interpret the intercept as: For male Germans (<code>frau</code> == 0) who were born in former West Germany (<code>ost</code> == 0) and with average years of education (<code>cpgbilzeit</code>) and average years of work experience (<code>cerf</code>), the expected hourly wage is 18,51 Euro/h.</p></li>
<li><p>One can now also predict the wages for other groups by adding the values of the coefficients and the intercept. E.g. The model predicts hourly wages of <code>18.51 - 2.75 = 15.76</code> Euro/h for females compared to 18.51 Euro/h for males, holding education and work experience equal.</p></li>
</ul>
</div>
<div id="work-experience-and-wage" class="section level3 tabset">
<h3>2.3 work experience and wage</h3>
<p>Is the relationship between work experience and wage linear?</p>
<hr />
<p>Labor market research found that the relationship of work and wage is not linear. In the cprplots one can see the that model that assumes linearity systematically overestimates people with long work experience. The solution to this would be to use the squared term of work experience in the model.</p>
<div id="stata-2" class="section level4">
<h4>Stata</h4>
<pre class="r"><code>knitr::include_graphics(&quot;out/cpr_2_3.png&quot;)</code></pre>
<p><img src="out/cpr_2_3.png" width="300px" /></p>
<pre class="r"><code>knitr::include_graphics(&quot;out/cpr_2_32.png&quot;)</code></pre>
<p><img src="out/cpr_2_32.png" width="300px" /></p>
<pre class="stata"><code>    
use &quot;_data/ex_mydf.dta&quot;, clear

    reg hwageb i.frau pgbilzeit erf ost if asample==1 &amp; syear==2015 [pw=phrf] 
    
    cprplot erf, msize(vsmall) jitter(2) mspline msopts(bands(11) lcolor(red)) name(cpr_2_3, replace)
    
    graph use cpr_2_3
    graph export &quot;out/cpr_2_3.png&quot;, replace
    
      reg hwageb i.frau##c.pgbilzeit c.erf##c.erf ost if asample==1 &amp; syear==2015 [pw=phrf] 
    cprplot erf, msize(vsmall) jitter(2) mspline msopts(bands(11) lcolor(red)) name(cpr_2_32, replace)
    
    graph use cpr_2_32
    graph export &quot;out/cpr_2_32.png&quot;, replace
    </code></pre>
<pre><code>
.         
. use &quot;_data/ex_mydf.dta&quot;, clear
(PGEN: Feb 12, 2017 13:00:53-1 DBV32L)

. 
.         reg hwageb i.frau pgbilzeit erf ost if asample==1 &amp; syear==2015 [pw=p
&gt; hrf] 
(sum of wgt is   3.3886e+07)

Linear regression                               Number of obs     =     14,218
                                                F(4, 14213)       =     259.84
                                                Prob &gt; F          =     0.0000
                                                R-squared         =     0.2253
                                                Root MSE          =     10.072

------------------------------------------------------------------------------
             |               Robust
      hwageb |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
        frau |
   weiblich  |  -2.754198   .2425546   -11.35   0.000    -3.229636   -2.278759
   pgbilzeit |   1.638184   .0619018    26.46   0.000     1.516848     1.75952
         erf |   .2431915   .0109426    22.22   0.000     .2217425    .2646405
         ost |  -4.278906   .2718054   -15.74   0.000     -4.81168   -3.746132
       _cons |  -6.573576   .7699179    -8.54   0.000    -8.082716   -5.064436
------------------------------------------------------------------------------

.         
.         cprplot erf, msize(vsmall) jitter(2) mspline msopts(bands(11) lcolor(
&gt; red)) name(cpr_2_3, replace)

.         
.         graph use cpr_2_3
file cpr_2_3.gph not found
r(601);

end of do-file
r(601);</code></pre>
</div>
<div id="r-2" class="section level4 tabset active">
<h4>R</h4>
<div id="models-1" class="section level5">
<h5>Models</h5>
<div id="base-model" class="section level6">
<h6>Base Model</h6>
<pre class="r"><code># base model
  fit2.3 &lt;- asample%&gt;% 
      filter(syear == 2015) %&gt;%
      lm(hwageb ~ frau + pgbilzeit + erf + ost, 
                      data= ., weights = phrf)
  
  tidy(fit2.3)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"-6.57","3":"0.4641","4":"-14","5":"3.1e-45"},{"1":"frau","2":"-2.75","3":"0.1737","4":"-16","5":"3.9e-56"},{"1":"pgbilzeit","2":"1.64","3":"0.0310","4":"53","5":"0.0e+00"},{"1":"erf","2":"0.24","3":"0.0076","4":"32","5":"9.0e-216"},{"1":"ost","2":"-4.28","3":"0.2223","4":"-19","5":"1.5e-81"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="exp-model-with-squared-experience" class="section level6">
<h6>2.3_exp model with squared experience</h6>
<pre class="r"><code>  fit2.3_exp &lt;- asample %&gt;%
       filter(syear == 2015) %&gt;%
       mutate(frau.d = factor(frau)) %&gt;% 
       lm(hwageb ~ frau + pgbilzeit + erf + I(erf^2) + ost, 
          data= ., weights = phrf)
  
  tidy(fit2.3_exp)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"-8.3531","3":"0.47902","4":"-17","5":"2.1e-67"},{"1":"frau","2":"-2.9144","3":"0.17298","4":"-17","5":"4.4e-63"},{"1":"pgbilzeit","2":"1.6162","3":"0.03087","4":"52","5":"0.0e+00"},{"1":"erf","2":"0.5853","3":"0.02610","4":"22","5":"1.9e-109"},{"1":"I(erf^2)","2":"-0.0088","3":"0.00064","4":"-14","5":"2.0e-42"},{"1":"ost","2":"-4.1916","3":"0.22092","4":"-19","5":"2.7e-79"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<div id="plots-1" class="section level5">
<h5>Plots</h5>
<div id="histogram-of-hourly-wage" class="section level6">
<h6>Histogram of Hourly Wage</h6>
<pre class="r"><code>  g_hist_wage</code></pre>
<p><img src="ex2_soep_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>  asample %&gt;% 
        filter(syear == 2015) %&gt;% 
        select(hwageb) %&gt;% 
        stat.desc(basic = T)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["hwageb"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"1.5e+04","_rn_":"nbr.val"},{"1":"7.3e+01","_rn_":"nbr.null"},{"1":"0.0e+00","_rn_":"nbr.na"},{"1":"0.0e+00","_rn_":"min"},{"1":"4.6e+02","_rn_":"max"},{"1":"4.6e+02","_rn_":"range"},{"1":"2.5e+05","_rn_":"sum"},{"1":"1.4e+01","_rn_":"median"},{"1":"1.7e+01","_rn_":"mean"},{"1":"9.7e-02","_rn_":"SE.mean"},{"1":"1.9e-01","_rn_":"CI.mean.0.95"},{"1":"1.4e+02","_rn_":"var"},{"1":"1.2e+01","_rn_":"std.dev"},{"1":"7.1e-01","_rn_":"coef.var"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Component + Residual Plot Note: These plots are not available if there is an interaction term in the model formula. It does work, if the interaction term is stored in an extra variable</p>
<pre class="r"><code>  crPlots(fit2.3, terms = .~ erf, layout = c(1,1))</code></pre>
<p><img src="ex2_soep_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>fit2.3_exp &lt;- asample %&gt;%
       filter(syear == 2015) %&gt;%
       mutate(erfq = erf*erf) %&gt;% 
       lm(hwageb ~ frau + pgbilzeit + erf + erfq + ost, 
          data= ., weights = phrf)

  crPlots(fit2.3_exp, terms = .~ erf, layout = c(1,1))</code></pre>
<p><img src="ex2_soep_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
</div>
</div>
</div>
<div id="log-model" class="section level3 tabset">
<h3>2.4 Log Model</h3>
<p>Specifiy the same regression model but use the natural logarithm as dependent variable instead. How does the the interpretation of coefficients change?</p>
<hr />
<p><strong>Why use log of wage?</strong> Hourly wage is very right skewed while the log(wage) is closer to a normal distribution. Since the dependent variable is now the log, it is not very intuitive to interpret.</p>
<p>How does the the interpretation of coefficients change? - before we had additive model now its a multiple model - you can be interpreted as percentage change - <code>dis exp(.0868897)</code> - e.g. 1.09 -&gt; for every more year of education, expected wage is raised by 9% - change after 8 years: <code>dis exp(.0868897)^8</code> = 2,003 -&gt; 100% increase</p>
<div id="stata-3" class="section level4">
<h4>Stata</h4>
<pre class="stata"><code>
use &quot;_data/ex_mydf.dta&quot;, clear
    
* Mincer-Equation
    reg lnhwageb pgbilzeit erf frau ost if asample==1 &amp; syear==2015 [pw=phrf]
    
* Standardization
      reg hwageb pgbilzeit frau erf ost if asample==1 &amp; syear==2015 [pw=phrf], beta
      
      dis exp(.0868897) // 0.08.. if coef. of yrs of education is constant
      dis  .3956569^2   // (beta coeff of yrs of education squared)</code></pre>
<pre><code>
. 
. use &quot;_data/ex_mydf.dta&quot;, clear
(PGEN: Feb 12, 2017 13:00:53-1 DBV32L)

.         
. * Mincer-Equation
.         reg lnhwageb pgbilzeit erf frau ost if asample==1 &amp; syear==2015 [pw=p
&gt; hrf]
variable lnhwageb not found
r(111);

end of do-file
r(111);</code></pre>
</div>
<div id="r-3" class="section level4 tabset active">
<h4>R</h4>
<div id="models-2" class="section level5">
<h5>Models</h5>
<div id="mincer-model" class="section level6">
<h6>Mincer Model</h6>
<pre class="r"><code> fit2.4 &lt;- asample %&gt;% 
        # filter because income variable has 0&#39;s
        filter(syear == 2015,
               hwageb &gt; 0) %&gt;% 
        lm(log(hwageb) ~ pgbilzeit + erf + frau + ost,
           data = ., weights = phrf)

 tidy(fit2.4)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"1.391","3":"0.02246","4":"62","5":"0.0e+00"},{"1":"pgbilzeit","2":"0.087","3":"0.00150","4":"58","5":"0.0e+00"},{"1":"erf","2":"0.015","3":"0.00037","4":"41","5":"0.0e+00"},{"1":"frau","2":"-0.135","3":"0.00841","4":"-16","5":"1.6e-57"},{"1":"ost","2":"-0.270","3":"0.01078","4":"-25","5":"1.5e-135"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="coefficients" class="section level6">
<h6>Coefficients</h6>
<p>How does the the interpretation of coefficients change? -&gt; before we had additive model now its a multiple model you can interpret this as percentage change Example: 1.09 -&gt; for every more year of education, expected wage is raised by 9%</p>
<pre class="r"><code>  exp(.0868897) # 0.08.. if coef. of yrs of education</code></pre>
<pre><code>## [1] 1.1</code></pre>
<p>if you want to know the change after 8 years:</p>
<pre class="r"><code>   exp(.0868897)^8   # 2,003 -&gt; 100% increase</code></pre>
<pre><code>## [1] 2</code></pre>
</div>
<div id="standardization" class="section level6">
<h6>standardization</h6>
<p>if you standardize you do it on both sides of the equations, (add , beta to command) then they are called beta- coeff.</p>
<p>interpretation: change of y in terms of its SD when x changes by 1 SD what is it useful for? - how to get them? - is good to interpret how large the effect is the square of beta coef. tell you portion of variance axplained by var of variable</p>
<ul>
<li><p>15 % of wage is due to variation in bilzeit issues, you can only do than in one model, not compare across models if you have interaction in your model, can (not?) interpret beta’s</p></li>
<li>standardization:
<ul>
<li>if you standardize you do it on both sides of the equations, (add , beta to command) then coefficients are called beta- coeff.</li>
<li>interpretation: change of y in terms of its SD when x changes by 1 SD</li>
<li>what is it useful for?</li>
<li>how to get them
<ul>
<li>is good to interpret how large the effect is</li>
<li>the square of beta coef. tell you portion of variance axplained by var of variable</li>
<li><code>dis  .3956569^2</code> (beta coeff of yrs of education squared)</li>
</ul></li>
<li>15 percent of wage is due to variation in years if education</li>
<li>issues, you can only do than in one model, not compare across models</li>
<li>if you have interaction in your model, can (not?) interpret beta’s</li>
</ul></li>
</ul>
<pre class="r"><code> # to do: betas
   # reg hwageb pgbilzeit frau erf ost if asample==1 &amp; syear==2015 [pw=phrf], beta 

  .3956569^2    # beta coeff of yrs of education squared</code></pre>
<pre><code>## [1] 0.16</code></pre>
</div>
</div>
</div>
</div>
<div id="gender-pay-gap" class="section level3 tabset">
<h3>2.5 Gender Pay Gap</h3>
<p>How large is the gender pay gap?</p>
<hr />
<p>to do: write answer</p>
<div id="stata-4" class="section level4">
<h4>Stata</h4>
<pre class="stata"><code>use &quot;_data/ex_mydf.dta&quot;, clear

reg lnhwageb ost frau pgbilzeit c.erf##c.erf pgexpue if asample==1 &amp; syear==2015 [pw=phrf]
margins  , at(erf=(0(5)50) pgbilzeit=(8 13 18))
marginsplot
dis exp(-.1437791)

* raw gap
reg lnhwageb frau if asample==1 &amp; syear==2015 [pw=phrf]
dis exp(-.1983373)
</code></pre>
<pre><code>
. use &quot;_data/ex_mydf.dta&quot;, clear
(PGEN: Feb 12, 2017 13:00:53-1 DBV32L)

. 
. reg lnhwageb ost frau pgbilzeit c.erf##c.erf pgexpue if asample==1 &amp; syear==2
&gt; 015 [pw=phrf]
variable lnhwageb not found
r(111);

end of do-file
r(111);</code></pre>
</div>
<div id="r-4" class="section level4 tabset active">
<h4>R</h4>
<div id="models-3" class="section level5">
<h5>Models</h5>
<pre class="r"><code>    # reg lnhwageb ost frau pgbilzeit c.erf##c.erf pgexpue if asample==1 &amp; syear==2015 [pw=phrf]
    # margins  , at(erf=(0(5)50) pgbilzeit=(8 13 18))
    # marginsplot
    exp(-.1437791)</code></pre>
<pre><code>## [1] 0.87</code></pre>
<pre class="r"><code>    # 
    # * raw gap
    # reg lnhwageb frau if asample==1 &amp; syear==2015 [pw=phrf]
    # 
    exp(-.1983373)</code></pre>
<pre><code>## [1] 0.82</code></pre>
</div>
</div>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
